TOP=..

include $(TOP)/configure/CONFIG

PROD_HOST += MathsService
MathsService_SRCS += MathsServiceMain.cpp
MathsService_SRCS += MathsService.cpp
MathsService_LIBS += pvAccess pvData Com

#PROD_HOST += MathsClient
#MathsClient_SRCS += MathsClient.cpp
#MathsClient_LIBS += pvAccess pvData Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

