#!/bin/sh
#
# hg flow example
#
# creates a complete example mercurial repository for hg flow in ./sample,
# and runs the usual commands necessary for a development and release schedule
#
# Author    Ralph Lange <Ralph.Lange@gmx.de>
# Copyright (C) 2013 Helmholtz-Zentrum Berlin für Materialien und Energie
#

# Exit on failure
set -e
# Show what you're doing
set -x

HGRC=~/.hgrc
REPO=sample

die () {
  echo "$1"
  return 1
}

################################################################################
# Check for hg flow extension being installed

grep "^[[:space:]]*flow[[:space:]]*=" $HGRC || die "hg flow extension must be installed (https://bitbucket.org/yujiewu/hgflow)"

################################################################################
# Create empty repository and add a few "legacy" commits

rm -fr $REPO/* $REPO/.hg*
#mkdir $REPO
cd $REPO

cat > file1 << EOF
This is a file called file1.
EOF

hg init
hg add file1
hg commit -m "Initial commit"

cat >> file1 << EOF
It has a history of previous develpment.
EOF

hg commit -m "Legacy: add second line to file1"

cat > file2 << EOF
This is a second legacy file, called file2.
EOF

hg add file2
hg commit -m "Legacy: add second file named file2"

sed -i -e 's/develpment/development/' file1
hg commit -m "Legacy: fix spelling in file1"

################################################################################
# Enable hg flow

# Usually this is done interactively, the first two answers are non-default:
# Branch name for master stream: [default] master
# Branch name for develop stream: [develop] default

cat > .hgflow << EOF
[branchname]
master = master
develop = default
feature = feature/
release = release/
hotfix = hotfix/
support = support/
EOF

hg flow init -f < /dev/null

################################################################################
# Simple development on develop trunk

hg flow develop

cat >> file1 << EOF
Added with a simple development commit directly on develop trunk.
EOF

hg commit -m "Simple development on develop trunk"

################################################################################
# Development on a feature branch

hg flow feature start addFile3

cat > file3 << EOF
This file added with a feature branch called 'addFile3'.
EOF

hg add file3
hg commit -m "Adding file3 on a feature branch"

cat >> file3 << EOF
Another change within the same feature branch.
The quick brown fox jumps over the lazy frog.
EOF

hg commit -m "Updating file3 on the feature branch"

hg flow feature addFile3
hg flow feature finish

################################################################################
# Release process

# Start the release branch

hg flow release start 1.0.0

# Prepare the -pre1 release

cat > RELEASE << EOF
Release: 1.0.0-pre1
EOF

hg add RELEASE
hg commit -m "Add RELEASE file"

hg tag 1.0.0-pre1

# Fix things and prepare the -rc1 release

cat >> file2 << EOF
This was fixed for the 1.0.0-rc1 release
EOF
cat > RELEASE << EOF
Release: 1.0.0-rc1
EOF

hg commit -m "Fix missing thing in file2"

hg tag 1.0.0-rc1

# Prepare final release

cat > RELEASE << EOF
Release: 1.0.0
EOF

hg commit -m "Prepare for release 1.0.0"

# Release

hg flow release finish

################################################################################
